### ISSUE TITLE
Dependencies for compilation of HRIBF-free version

### ISSUE THREAD

**Issue by kmiernik** [pixie16/pixie_scan#21]
In order to compile pixie_scan in his_drr branch one needs the PixieSuite2 installed (the Unpacker is included in Scanner.cpp). The pixie_scan should be independent from PixieSuite2. Particularly for off-line analysis or debugging, the dependency on PixieSuite is unneeded. What is more the PixieSuite2 requires PLX and PXI proprietary drivers and may make the installation not possible.

**Comment by spaulaus** [comment]
@kmiernik : PixieSuite2 does not need PLX or PXI installed to install properly. If you compile with the -DUSE_SCAN=OFF flag then it removes these dependencies from the compilation. The dependency on PixieSuite2 is absolutely critical since it provides us with a unified control interface, as well as some useful libraries. All of these updates are in accordance with the next generation software suite that we are developing called the Pixie Analysis and Acquisition Software Suite (PAASS). 

The version of the scan code you are using is a hacked (3 day dev time) version of the software to remove the HRIBF libraries. It is not in any way a final version, and I explicitly mentioned this previously. This branch was a necessary first step to the final removal of the HRIBF dependencies. It allowed us to benchmark the time and understand the scope of trying to remove these libraries. 

Rest assured we are working dilligently to complete this transition, but are plagued with the same problems as everybody else.

**Comment by ksmith0** [comment]
Also, this dependence is exactly the same as it was previously with pixie_scan dependent on acq2 and upak libraries.
